CREATE DATABASE gow;


USE DATABASE gow;


CREATE TABLE `APP_CONFIG` (
  `CONFIG_NAME` varchar(50) NOT NULL,
  `CONFIG_VALUE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`CONFIG_NAME`) 
) ;

CREATE TABLE `AUDIT_BLACKLIST_DOMAIN_MASTER` (
  `ROW_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOMAIN_NAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ROW_ID`) 
);


CREATE TABLE `AUDIT_REQUEST_CONTENT` (
  `ARM_ROW_ID` char(20) DEFAULT NULL,
  `CONTENT_FULL` varchar(4000) DEFAULT NULL
);




CREATE TABLE `AUDIT_REQUEST_MASTER` (
  `ARM_ROW_ID` char(20) DEFAULT NULL,
  `USER_ID` varchar(100) DEFAULT NULL,
  `USER_IP_ADDR` varchar(39) DEFAULT NULL,
  `USER_ACTION` char(1) DEFAULT NULL COMMENT 'C-Copy, P-Paste, U-Url access',
  `CONTENT_SHORT` varchar(30) DEFAULT NULL,
  `URL_DOMAIN` varchar(30) DEFAULT NULL,
  `URL_PATH` varchar(30) DEFAULT NULL,
  `CREATED_DATETIME` timestamp NULL DEFAULT NULL,
  `TIME_ZONE` varchar(64) DEFAULT NULL COMMENT 'IST, UTC'
);
CREATE TABLE `AUDIT_TAGS_MASTER` (
  `TAG_NAME` varchar(30) DEFAULT NULL,
  `TAG_TYPE` char(1) DEFAULT NULL COMMENT 'C-Critical, W-Warning, I-Ignore'
);




CREATE TABLE `AUDIT_USER_SEARCH_CONTENT_MAPPING` (
  `AUSM_ID` varchar(20) DEFAULT NULL,
  `ARM_ROW_ID` varchar(20) DEFAULT NULL,
  `CREATED_DT` timestamp NULL DEFAULT NULL
);



CREATE TABLE `AUDIT_USER_SEARCH_MASTER` (
  `AUSM_ID` varchar(20) NOT NULL,
  `USER_ID` varchar(50) DEFAULT NULL,
  `CREATED_DT` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`AUSM_ID`) 
);



CREATE TABLE `AUDIT_USER_SEARCH_TAGS` (
  `ROW_ID` varchar(20) NOT NULL,
  `AUSM_ID` varchar(20) DEFAULT NULL,
  `TAG_NAME` varchar(100) DEFAULT NULL,
  `CREATED_DT` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ROW_ID`) 
);



CREATE TABLE `FAKE_DATA_REQUEST_MASTER` (
  `ROW_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTENT` varchar(4000) DEFAULT NULL,
  PRIMARY KEY (`ROW_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30001;




CREATE TABLE `FAKE_DOMAIN_NAME_MASTER` (
  `DOMAIN_NAME` varchar(50) NOT NULL,
  PRIMARY KEY (`DOMAIN_NAME`) 
);




CREATE TABLE `FAKE_DOMAIN_NAME_MASTER` (
  `DOMAIN_NAME` varchar(50) NOT NULL,
  PRIMARY KEY (`DOMAIN_NAME`) 
);


CREATE TABLE `FAKE_USERNAME_MASTER` (
  `USERNAME` varchar(50) NOT NULL,
  PRIMARY KEY (`USERNAME`) 
);

INSERT INTO gow.APP_CONFIG
(CONFIG_NAME, CONFIG_VALUE)
VALUES('GPT_LAST_RUN', '2024-01-17 21:20:00');

