CREATE DATABASE gow;


USE DATABASE gow;


CREATE TABLE `APP_CONFIG` (
  `CONFIG_NAME` varchar(50) NOT NULL,
  `CONFIG_VALUE` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`CONFIG_NAME`) 
) ;

CREATE TABLE `AUDIT_BLACKLIST_DOMAIN_MASTER` (
  `ROW_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DOMAIN_NAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ROW_ID`) 
);

-- AIMON.AUDIT_REQUEST_CONTENT definition

CREATE TABLE `AUDIT_REQUEST_CONTENT` (
  `ARM_ROW_ID` char(20) DEFAULT NULL,
  `CONTENT_FULL` varchar(4000) DEFAULT NULL
);


-- AIMON.AUDIT_REQUEST_MASTER definition

CREATE TABLE `AUDIT_REQUEST_MASTER` (
  `ARM_ROW_ID` char(20) DEFAULT NULL,
  `USER_ID` varchar(100) DEFAULT NULL,
  `USER_IP_ADDR` varchar(39) DEFAULT NULL,
  `USER_ACTION` char(1) DEFAULT NULL COMMENT 'C-Copy, P-Paste, U-Url access',
  `CONTENT_SHORT` varchar(30) DEFAULT NULL,
  `URL_DOMAIN` varchar(30) DEFAULT NULL,
  `URL_PATH` varchar(30) DEFAULT NULL,
  `CREATED_DATETIME` timestamp NULL DEFAULT NULL,
  `TIME_ZONE` varchar(64) DEFAULT NULL COMMENT 'IST, UTC'
);
